apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-11-28T19:22:24Z"
  name: nexus-service
  namespace: nexus
  resourceVersion: "435403"
  uid: 236a10c7-8458-43c5-b5f9-eccda0be8d09
spec:
  clusterIP: 10.43.205.139
  clusterIPs:
    - 10.43.205.139
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 32000
  selector:
    app: nexus-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
