apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"usb-workernode1-pv"},"spec":{"accessModes":["ReadWriteMany"],"capacity":{"storage":"100Gi"},"local":{"path":"/usbmount"},"nodeAffinity":{"required":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"kubernetes.io/hostname","operator":"In","values":["workernode1"]}]}]}},"persistentVolumeReclaimPolicy":"Delete","storageClassName":"local-storage","volumeMode":"Filesystem"}}
  creationTimestamp: "2022-11-21T14:24:14Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: usb-workernode1-pv
  resourceVersion: "31394"
  uid: 361bcaa5-fbb8-42c2-adca-bfcb980dd7d7
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /usbmount
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - workernode1
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  volumeMode: Filesystem
status:
  phase: Available
